# GENERATED BY BRILLIANT AR STUDIO Do not modify this file directly
import display as d

class new_screen:
	def __init__(self):
		self.screen = [
			d.Polyline([299,80,294,232,449,228,299,78,459,70,295,231,172,2], 0xafafaf, thickness=1),
			d.Text('Double click to start', 128, 40, 0xafafaf, justify=d.TOP_LEFT),
		]
		self.screen.display()
